apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      securityContext:
        fsGroup: 70
        runAsUser: 70
      containers:
        - env:
            - name: POSTGRES_DB
              value: metering
            - name: POSTGRES_PASSWORD
              value: testpass
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: timescale/timescaledb:latest-pg12
          imagePullPolicy: IfNotPresent
          name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
