apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  selector:
    app: timescaledb
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
