apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      remoteWrite:
      - url: "http://exporter.tflannag.svc.cluster.local:9201/write"
        writeRelabelConfigs:
          - sourceLabels: [__name__]
            regex: 'metering:(.*)'
            action: keep
