apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tflannag-postgres-service-account
  labels:
    app: postgres
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
