apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tflannag-presto-service-account
  labels:
    app: presto
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
