apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tflannag-presto-service-account
  labels:
    app: presto
subjects:
- kind: ServiceAccount
  name: presto
  namespace: tflannag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tflannag-presto-service-account
