apiVersion: v1
kind: Service
metadata:
  name: exporter
  labels:
    app: exporter
spec:
  selector:
    app: exporter
  type: ClusterIP
  ports:
    - name: connector-port
      port: 9201
      protocol: TCP
